version: '3.8'
services:
  processor:
    image: prefixy/processor:0.1.0
  api:
    image: prefixy/api:0.1.0
    ports:
      - '8080:8080'
  redis:
    image: redis/redis-stack:7.2.0-v8
    restart: always
    ports:
      - '6379:6379'
  redpanda:
    image: vectorized/redpanda:v23.3.1-arm64
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - '--kafka-addr'
      - 'PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
      - '--advertise-kafka-addr'
      - 'PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092'
      - --check=false
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
