version: '3.8'
services:
  redpanda:
    image: vectorized/redpanda:v23.3.1-arm64
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - '--kafka-addr'
      - 'PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
      - '--advertise-kafka-addr'
      - 'PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092'
      - --check=false
